# Generated by Django 2.1.4 on 2019-11-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_san_pham', models.CharField(max_length=200, unique=True, verbose_name='Ten san pham')),
                ('hinh', models.ImageField(blank=True, upload_to='hinh_san_pham', verbose_name='Hinh')),
                ('don_gia_ban', models.FloatField(verbose_name='Don gia')),
                ('mo_ta_tom_tat', models.CharField(max_length=200, verbose_name='Tom tat')),
                ('chi_tiet', models.TextField(verbose_name='Chi tiet')),
                ('trang_thai', models.BooleanField(blank=True, default=True, verbose_name='Trang thai')),
            ],
        ),
    ]
