# Generated by Django 2.2.7 on 2019-11-24 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ten_khach_hang', models.CharField(max_length=200, unique=True, verbose_name='Ten khach hang')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('trang_thai', models.BooleanField(blank=True, default=True, verbose_name='Trang thai')),
            ],
        ),
    ]
