# Generated by Django 2.2.7 on 2019-11-24 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
