# Generated by Django 2.2.7 on 2019-11-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0003_auto_20191124_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
